Repository Solvro/backend-topwr-sks, pull requests merged in 2024-11, with the labels that each got.

#18 feat/sks users wrapper
  app/controllers/sks_users_controller.ts
  app/models/sks_user.ts
  commands/scrape_menu.ts
  commands/scrape_users.ts
  database/migrations/1730994081410_create_sks_users_table.ts
  scripts/menu_scrapper.ts
  scripts/users_scrapper.ts
  start/routes.ts
  start/scheduler.ts
Labels: enhancement

#21 fix/remove id to save space
  app/models/sks_user.ts
  database/migrations/1730994081410_create_sks_users_table.ts
Labels: bug

#22 docs/update readme
  README.md
  assets/schema2.png
Labels: documentation

#23 fix/improve error handling
  scripts/menu_scrapper.ts
Labels: bug

#25 feat/archive previous menus
  app/controllers/meals_controller.ts
  app/models/hashes_meal.ts
  app/models/meal.ts
  app/models/website_hash.ts
  database/migrations/1730118314055_create_meals_table.ts
  database/migrations/1730118875276_create_website_hashes_table.ts
  database/migrations/1731367612817_create_hashes_meals_table.ts
  scripts/menu_scrapper.ts
  start/routes.ts
Labels: enhancement

#29 fix/portion size parsing
  package-lock.json
  package.json
  scripts/menu_scrapper.ts
  tests/fixtures/external_menu_response.html
  tests/fixtures/parsed_menu_expected_response.ts
  tests/unit/menuScrapper/scrape_menu.spec.ts
Labels: bug

#24 docs/add swagger docs
  Dockerfile
  app/controllers/meals_controller.ts
  app/controllers/sks_users_controller.ts
  app/models/hashes_meal.ts
  app/models/meal.ts
  app/models/sks_user.ts
  app/models/website_hash.ts
  commands/docs_generate.ts
  config/swagger.ts
  package-lock.json
  package.json
  start/routes.ts
  swagger.json
  swagger.yml
Labels: documentation
